# Generated by Django 5.1.2 on 2024-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_shop', '0003_remove_ticket_user_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
