# Generated by Django 5.1.2 on 2024-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_shop', '0006_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
