# Generated by Django 5.1.2 on 2024-12-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_shop', '0008_order_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
