# Generated by Django 5.1.2 on 2025-01-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_shop', '0012_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
